quanlydiemthi
USE quanlydiemthi;
CREATE TABLE HocSinh(
MaHS VARCHAR(20) PRIMARY KEY,
TenHS VARCHARACTER(50),
NgaySinh DATETIME,
Lop VARCHAR(20),
GT VARCHAR(20)
);
CREATE TABLE MonHoc(
MaMH VARCHAR(20) PRIMARY KEY,
TenMH VARCHAR(50)
);
CREATE TABLE BangDiem(
MaHS VARCHAR (20),
MaMH VARCHAR (20),
DiemThi INT ,
NgayKT DATETIME,
PRIMARY KEY (MaHS, MaMH),
FOREIGN KEY(MaHS) REFERENCES HocSinh(MaHS),
FOREIGN KEY (MaMH) REFERENCES MonHoc(MaMH)nhacungcap
);
CREATE TABLE GiaoVien(
MaGV VARCHAR (20) PRIMARY KEY,
TenGV VARCHAR (20),
SDT VARCHAR(10)
);
bangdiem
